# Generated by Django 5.2.1 on 2025-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosocoTableA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('nr', models.CharField(blank=True, max_length=50, null=True)),
                ('wr', models.CharField(blank=True, max_length=50, null=True)),
                ('sr', models.CharField(blank=True, max_length=50, null=True)),
                ('er', models.CharField(blank=True, max_length=50, null=True)),
                ('ner', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('report_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posoco_posocotablea',
            },
        ),
        migrations.CreateModel(
            name='PosocoTableG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=255)),
                ('nr', models.CharField(blank=True, max_length=50, null=True)),
                ('wr', models.CharField(blank=True, max_length=50, null=True)),
                ('sr', models.CharField(blank=True, max_length=50, null=True)),
                ('er', models.CharField(blank=True, max_length=50, null=True)),
                ('ner', models.CharField(blank=True, max_length=50, null=True)),
                ('all_india', models.CharField(blank=True, max_length=50, null=True)),
                ('share_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('report_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posoco_posocotableg',
            },
        ),
    ]
