# Generated by Django 5.2.1 on 2025-10-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('script_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='IDLE', max_length=20)),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('last_success_time', models.DateTimeField(blank=True, null=True)),
                ('is_data_available_today', models.BooleanField(default=False)),
                ('log_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['script_name'],
            },
        ),
    ]
