# Generated by Django 5.2.1 on 2025-09-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrldc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrldc2cdata',
            name='ace_max',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2cdata',
            name='ace_min',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2cdata',
            name='requirement_at_max_demand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2cdata',
            name='shortage_during_max_demand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
