# Generated by Django 5.2.1 on 2025-09-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrldc_app', '0002_alter_wrldc2cdata_ace_max_alter_wrldc2cdata_ace_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrldc2adata',
            name='availability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='consumption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='drawal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='gas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='hydro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='net_sch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='others',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='requirement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='shortage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='solar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='thermal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='ui',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wrldc2adata',
            name='wind',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
