# Generated by Django 5.2.1 on 2025-09-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrldc_app', '0003_alter_wrldc2adata_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wrldc2cdata',
            old_name='max_demand_met_of_the_day',
            new_name='max_demand_day',
        ),
    ]
