# Generated by Django 5.2.1 on 2025-09-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrldc_app', '0004_rename_max_demand_met_of_the_day_wrldc2cdata_max_demand_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wrldc2cdata',
            old_name='requirement_at_max_demand',
            new_name='req_max_demand',
        ),
        migrations.RenameField(
            model_name='wrldc2cdata',
            old_name='shortage_during_max_demand',
            new_name='shortage_max_demand',
        ),
    ]
