# Generated by Django 5.2.1 on 2025-08-08 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Srldc2AData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('thermal', models.FloatField(blank=True, null=True)),
                ('hydro', models.FloatField(blank=True, null=True)),
                ('gas_naptha_diesel', models.FloatField(blank=True, null=True)),
                ('solar', models.FloatField(blank=True, null=True)),
                ('wind', models.FloatField(blank=True, null=True)),
                ('others', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('net_sch', models.FloatField(blank=True, null=True)),
                ('drawal', models.FloatField(blank=True, null=True)),
                ('ui', models.FloatField(blank=True, null=True)),
                ('availability', models.FloatField(blank=True, null=True)),
                ('demand_met', models.FloatField(blank=True, null=True)),
                ('shortage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Table 2A Data',
                'verbose_name_plural': 'Table 2A Data',
                'unique_together': {('report_date', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Srldc2CData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('max_demand_met_of_the_day', models.FloatField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('shortage_during_max_demand', models.FloatField(blank=True, null=True)),
                ('requirement_at_max_demand', models.FloatField(blank=True, null=True)),
                ('demand_met_max_requirement', models.FloatField(blank=True, null=True)),
                ('time_max_requirement', models.CharField(blank=True, max_length=50, null=True)),
                ('shortage_during_max_requirement', models.FloatField(blank=True, null=True)),
                ('max_requirement_day', models.FloatField(blank=True, null=True)),
                ('ace_max', models.FloatField(blank=True, null=True)),
                ('time_ace_max', models.CharField(blank=True, max_length=50, null=True)),
                ('ace_min', models.FloatField(blank=True, null=True)),
                ('time_ace_min', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Table 2C Data',
                'verbose_name_plural': 'Table 2C Data',
                'unique_together': {('report_date', 'state')},
            },
        ),
    ]
