# Generated by Django 5.2.1 on 2025-09-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srldc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srldc2cdata',
            old_name='demand_met_max_requirement',
            new_name='demand_max_req',
        ),
        migrations.RenameField(
            model_name='srldc2cdata',
            old_name='max_demand_met_of_the_day',
            new_name='max_demand',
        ),
        migrations.RenameField(
            model_name='srldc2cdata',
            old_name='max_requirement_day',
            new_name='max_req_day',
        ),
        migrations.RenameField(
            model_name='srldc2cdata',
            old_name='requirement_at_max_demand',
            new_name='req_max_demand',
        ),
        migrations.RenameField(
            model_name='srldc2cdata',
            old_name='shortage_during_max_demand',
            new_name='shortage_max_demand',
        ),
        migrations.RenameField(
            model_name='srldc2cdata',
            old_name='shortage_during_max_requirement',
            new_name='shortage_max_req',
        ),
        migrations.RenameField(
            model_name='srldc2cdata',
            old_name='time_max_requirement',
            new_name='time_max_req',
        ),
    ]
