# Generated by Django 5.2.1 on 2025-09-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srldc_app', '0002_rename_demand_met_max_requirement_srldc2cdata_demand_max_req_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srldc2adata',
            name='total',
        ),
    ]
