# Generated by Django 5.2.1 on 2025-09-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrldc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nrldc2adata',
            old_name='other_biomass_co_gen_etc',
            new_name='other_biomass',
        ),
    ]
