# Generated by Django 5.2.1 on 2025-09-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrldc_app', '0002_rename_other_biomass_co_gen_etc_nrldc2adata_other_biomass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nrldc2cdata',
            old_name='max_demand_met_of_the_day',
            new_name='max_demand_met',
        ),
    ]
