# Generated by Django 5.2.1 on 2025-09-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrldc_app', '0003_rename_max_demand_met_of_the_day_nrldc2cdata_max_demand_met'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nrldc2cdata',
            old_name='max_demand_met',
            new_name='max_demand',
        ),
    ]
