# Generated by Django 5.2.1 on 2025-09-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrldc_app', '0004_rename_max_demand_met_nrldc2cdata_max_demand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nrldc2cdata',
            old_name='demand_met_at_max_requirement',
            new_name='demand_met_max_req',
        ),
        migrations.RenameField(
            model_name='nrldc2cdata',
            old_name='max_requirement_of_the_day',
            new_name='max_req_day',
        ),
        migrations.RenameField(
            model_name='nrldc2cdata',
            old_name='requirement_at_max_demand',
            new_name='req_max_demand',
        ),
        migrations.RenameField(
            model_name='nrldc2cdata',
            old_name='shortage_during_max_demand',
            new_name='shortage_during',
        ),
        migrations.RenameField(
            model_name='nrldc2cdata',
            old_name='shortage_during_max_requirement',
            new_name='shortage_max_req',
        ),
        migrations.RenameField(
            model_name='nrldc2cdata',
            old_name='time_max_demand_met',
            new_name='time_max',
        ),
        migrations.RenameField(
            model_name='nrldc2cdata',
            old_name='time_max_requirement',
            new_name='time_max_req',
        ),
        migrations.RenameField(
            model_name='nrldc2cdata',
            old_name='time_min_demand_met',
            new_name='time_min_demand',
        ),
    ]
